services:

  php-test:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - .env
      - .env.dev
      - .env.test
