services:

  nginx:
    image: nginx:1.29-alpine3.22
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - '8000:80'
    depends_on:
      - php

  php:
    image: mcp-server:dev
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - ./:/app
    working_dir: /app
